
package rgs.ag.sportradar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.ArrayOfApproveRequest;
import org.datacontract.schemas._2004._07.ArrayOfCancelRequest;
import org.datacontract.schemas._2004._07.ArrayOfGenericResponse;
import org.datacontract.schemas._2004._07.ArrayOfManualPaymentRequest;
import org.datacontract.schemas._2004._07.ArrayOfPaymentRequest;
import org.datacontract.schemas._2004._07.ArrayOfQueryBalanceRequest;
import org.datacontract.schemas._2004._07.ArrayOfReserveFundsRequest;
import org.datacontract.schemas._2004._07.ArrayOfUserInfoRequest;
import org.datacontract.schemas._2004._07.ArrayOfUserInfoResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://sportradar.ag.rgs/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.ObjectFactory.class,
    rgs.ag.sportradar.ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @param requests
     * @param secretKey
     * @return
     *     returns org.datacontract.schemas._2004._07.ArrayOfUserInfoResponse
     */
    @WebMethod(action = "http://sportradar.ag.rgs/IService/userInfo")
    @WebResult(name = "userInfoResult", targetNamespace = "http://sportradar.ag.rgs/")
    @RequestWrapper(localName = "userInfo", targetNamespace = "http://sportradar.ag.rgs/", className = "rgs.ag.sportradar.UserInfo")
    @ResponseWrapper(localName = "userInfoResponse", targetNamespace = "http://sportradar.ag.rgs/", className = "rgs.ag.sportradar.UserInfoResponse")
    public ArrayOfUserInfoResponse userInfo(
        @WebParam(name = "secretKey", targetNamespace = "http://sportradar.ag.rgs/")
        String secretKey,
        @WebParam(name = "requests", targetNamespace = "http://sportradar.ag.rgs/")
        ArrayOfUserInfoRequest requests);

    /**
     * 
     * @param requests
     * @param secretKey
     * @return
     *     returns org.datacontract.schemas._2004._07.ArrayOfGenericResponse
     */
    @WebMethod(action = "http://sportradar.ag.rgs/IService/queryBalance")
    @WebResult(name = "queryBalanceResult", targetNamespace = "http://sportradar.ag.rgs/")
    @RequestWrapper(localName = "queryBalance", targetNamespace = "http://sportradar.ag.rgs/", className = "rgs.ag.sportradar.QueryBalance")
    @ResponseWrapper(localName = "queryBalanceResponse", targetNamespace = "http://sportradar.ag.rgs/", className = "rgs.ag.sportradar.QueryBalanceResponse")
    public ArrayOfGenericResponse queryBalance(
        @WebParam(name = "secretKey", targetNamespace = "http://sportradar.ag.rgs/")
        String secretKey,
        @WebParam(name = "requests", targetNamespace = "http://sportradar.ag.rgs/")
        ArrayOfQueryBalanceRequest requests);

    /**
     * 
     * @param requests
     * @param secretKey
     * @return
     *     returns org.datacontract.schemas._2004._07.ArrayOfGenericResponse
     */
    @WebMethod(action = "http://sportradar.ag.rgs/IService/reserveFunds")
    @WebResult(name = "reserveFundsResult", targetNamespace = "http://sportradar.ag.rgs/")
    @RequestWrapper(localName = "reserveFunds", targetNamespace = "http://sportradar.ag.rgs/", className = "rgs.ag.sportradar.ReserveFunds")
    @ResponseWrapper(localName = "reserveFundsResponse", targetNamespace = "http://sportradar.ag.rgs/", className = "rgs.ag.sportradar.ReserveFundsResponse")
    public ArrayOfGenericResponse reserveFunds(
        @WebParam(name = "secretKey", targetNamespace = "http://sportradar.ag.rgs/")
        String secretKey,
        @WebParam(name = "requests", targetNamespace = "http://sportradar.ag.rgs/")
        ArrayOfReserveFundsRequest requests);

    /**
     * 
     * @param requests
     * @param secretKey
     * @return
     *     returns org.datacontract.schemas._2004._07.ArrayOfGenericResponse
     */
    @WebMethod(action = "http://sportradar.ag.rgs/IService/payment")
    @WebResult(name = "paymentResult", targetNamespace = "http://sportradar.ag.rgs/")
    @RequestWrapper(localName = "payment", targetNamespace = "http://sportradar.ag.rgs/", className = "rgs.ag.sportradar.Payment")
    @ResponseWrapper(localName = "paymentResponse", targetNamespace = "http://sportradar.ag.rgs/", className = "rgs.ag.sportradar.PaymentResponse")
    public ArrayOfGenericResponse payment(
        @WebParam(name = "secretKey", targetNamespace = "http://sportradar.ag.rgs/")
        String secretKey,
        @WebParam(name = "requests", targetNamespace = "http://sportradar.ag.rgs/")
        ArrayOfPaymentRequest requests);

    /**
     * 
     * @param requests
     * @param secretKey
     * @return
     *     returns org.datacontract.schemas._2004._07.ArrayOfGenericResponse
     */
    @WebMethod(action = "http://sportradar.ag.rgs/IService/approve")
    @WebResult(name = "approveResult", targetNamespace = "http://sportradar.ag.rgs/")
    @RequestWrapper(localName = "approve", targetNamespace = "http://sportradar.ag.rgs/", className = "rgs.ag.sportradar.Approve")
    @ResponseWrapper(localName = "approveResponse", targetNamespace = "http://sportradar.ag.rgs/", className = "rgs.ag.sportradar.ApproveResponse")
    public ArrayOfGenericResponse approve(
        @WebParam(name = "secretKey", targetNamespace = "http://sportradar.ag.rgs/")
        String secretKey,
        @WebParam(name = "requests", targetNamespace = "http://sportradar.ag.rgs/")
        ArrayOfApproveRequest requests);

    /**
     * 
     * @param requests
     * @param secretKey
     * @return
     *     returns org.datacontract.schemas._2004._07.ArrayOfGenericResponse
     */
    @WebMethod(action = "http://sportradar.ag.rgs/IService/cancel")
    @WebResult(name = "cancelResult", targetNamespace = "http://sportradar.ag.rgs/")
    @RequestWrapper(localName = "cancel", targetNamespace = "http://sportradar.ag.rgs/", className = "rgs.ag.sportradar.Cancel")
    @ResponseWrapper(localName = "cancelResponse", targetNamespace = "http://sportradar.ag.rgs/", className = "rgs.ag.sportradar.CancelResponse")
    public ArrayOfGenericResponse cancel(
        @WebParam(name = "secretKey", targetNamespace = "http://sportradar.ag.rgs/")
        String secretKey,
        @WebParam(name = "requests", targetNamespace = "http://sportradar.ag.rgs/")
        ArrayOfCancelRequest requests);

    /**
     * 
     * @param requests
     * @param secretKey
     * @return
     *     returns org.datacontract.schemas._2004._07.ArrayOfGenericResponse
     */
    @WebMethod(action = "http://sportradar.ag.rgs/IService/manualPayment")
    @WebResult(name = "manualPaymentResult", targetNamespace = "http://sportradar.ag.rgs/")
    @RequestWrapper(localName = "manualPayment", targetNamespace = "http://sportradar.ag.rgs/", className = "rgs.ag.sportradar.ManualPayment")
    @ResponseWrapper(localName = "manualPaymentResponse", targetNamespace = "http://sportradar.ag.rgs/", className = "rgs.ag.sportradar.ManualPaymentResponse")
    public ArrayOfGenericResponse manualPayment(
        @WebParam(name = "secretKey", targetNamespace = "http://sportradar.ag.rgs/")
        String secretKey,
        @WebParam(name = "requests", targetNamespace = "http://sportradar.ag.rgs/")
        ArrayOfManualPaymentRequest requests);

}
